# Permalinks
permalink:           pretty

# Setup
title:               T.J. Bowling
tagline:             A Very Serious Series of Cat Pictures
url:                 http://gpsbach.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Timothy Bowling
  url:               https://twitter.com/gpsbach
  email:             timothy.bowling@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/gpsbach

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
